import type { Metadata } from "next";
import { Toaster } from "@/components/ui";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EduChain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en">
        <body className={inter.className}>
         <Providers>{children}</Providers>
        </body>
        <Toaster />
      </html>
  );
}
